name: CI/CD GreenCity
# Controls when the action will run.

concurrency: Testing

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: dev
  pull_request:
    branches: dev

env:
  userRepoName: core

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Run a multi-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          git fetch --unshallow
          mvn formatter:format; mvn clean install sonar:sonar -Dsonar.projectKey=OlhenShu_GreenCityUserMVPTemplate -Dsonar.organization=olhenshu -Dsonar.host.url=https://sonarcloud.io -Dsonar.binaries=target/classes -Dsonar.dynamicAnalysis=reuseReports

      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: Tests Report
          path: ${{ env.userRepoName }}/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Set outputs
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
